# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'pipelines-docker'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'devce2petcdpmaacr01-service-connection'
    repository: 'seaslug'
    command: 'pull'
    arguments: "seaslug:version-v1.0.0"
- task: Docker@2
  inputs:
    containerRegistry: 'YourDockerRegistryServiceConnection'
    command: 'tag'
    arguments: 'devce2petcdpmaacr01-service-connection/seaslug:version-v1.0.0 prdce2petcdpmaacr01-service-connection/seaslug:version-v1.0.0'
- task: Docker@2
  inputs:
    containerRegistry: 'prdce2petcdpmaacr01-service-connection'
    repository: 'seaslug'
    command: 'push'
    tags: 'version-v1.0.0'


 
